management:
  health:
    diskspace.enabled: false

server:
  port: 9090

logging:
  file: ./logs/service.log
  level:
    root: info
    org.springframework: error
    br.com.step: debug
  pattern: "[%d{ISO8601}] %-5level %-40c{1.} : %m%ex%n"


service:
  name: stepxml-converter
  version: 0.0.1

  stepxml:
    path: /Users/igce/Desenvolvimento
    extension: .xml