version: '3'
services:
  consul-server:
    image: consul:latest
    hostname: consul-server
    command: agent -server -bootstrap -ui -client 0.0.0.0 -dns-port 53 -recursor 8.8.8.8 -recursor 10.100.63.236 -recursor 172.16.136.40
    enviroment:
      - 'CONSUL_BIND_INTERFACE=eth0'
      - 'CONSUL_ALLOW_PREVILEGED_PORTS='
    ports:
      - '8500:8500'
    deploy:
      mode: replicated
      replicas: 1